/// ocaml-magic

/*
Copyright (c) 2014, Sang Kil Cha
All rights reserved.
This software is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License version 2, with the special exception on linking
described in file LICENSE.

This software is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
*/

typedef [abstract,ptr] void* magic_ptr;

magic_ptr init_magic( [out] int* r, [in,string] const char* filename, int flag );
void destroy_magic( magic_ptr p );

[string] char* from_file( magic_ptr p, [string] const char* filename );

